import {defineArrayMember, defineField, defineType} from 'sanity'
import {GalleryImageMemberInput} from '../studio/GalleryImageMemberInput'
import {PropertyGalleryInput} from '../studio/PropertyGalleryInput'

const WEBSITE = 'website'
const MEDIA_PHOTOS = 'mediaPhotos'
const MEDIA_DOCS = 'mediaDocs'
const SEO = 'seo'
/** Old dataset keys — hidden so Studio does not show “unknown fields”; remove after a one-time migration if you want a clean schema. */
const LEGACY = 'legacy'

export const propertyType = defineType({
  name: 'property',
  title: 'Property',
  type: 'document',
  groups: [
    {name: WEBSITE, title: 'Website listing', default: true},
    {name: MEDIA_PHOTOS, title: 'Photos & gallery'},
    {name: MEDIA_DOCS, title: 'Plans & downloads'},
    {name: SEO, title: 'SEO'},
    {name: LEGACY, title: 'Legacy (hidden)', hidden: true},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: WEBSITE,
      validation: (rule) => rule.required().max(70),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: WEBSITE,
      options: {source: 'title'},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'status',
      title: 'Listing status (website)',
      type: 'string',
      group: WEBSITE,
      options: {
        list: [
          {title: 'Buy (for sale)', value: 'for-sale'},
          {title: 'Rent', value: 'for-rent'},
          {title: 'Sold', value: 'sold'},
          {title: 'Reserved', value: 'reserved'},
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'propertyType',
      title: 'Property type',
      type: 'string',
      group: WEBSITE,
      options: {
        list: [
          {title: 'Apartment', value: 'apartment'},
          {title: 'Villa', value: 'villa'},
          {title: 'House', value: 'house'},
          {title: 'Penthouse', value: 'penthouse'},
          {title: 'Land', value: 'land'},
          {title: 'Office', value: 'office'},
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'price',
      title: 'Price',
      type: 'number',
      group: WEBSITE,
    }),
    defineField({
      name: 'currency',
      title: 'Currency',
      type: 'string',
      group: WEBSITE,
      initialValue: 'EUR',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'location',
      title: 'Location (label)',
      type: 'string',
      group: WEBSITE,
    }),
    defineField({
      name: 'address',
      title: 'Address',
      type: 'string',
      group: WEBSITE,
    }),
    defineField({
      name: 'bedrooms',
      title: 'Bedrooms',
      type: 'number',
      group: WEBSITE,
    }),
    defineField({
      name: 'bathrooms',
      title: 'Bathrooms',
      type: 'number',
      group: WEBSITE,
    }),
    defineField({
      name: 'internalArea',
      title: 'Internal area (m²)',
      type: 'number',
      group: WEBSITE,
    }),
    defineField({
      name: 'plotSize',
      title: 'Plot size (m²)',
      type: 'number',
      group: WEBSITE,
    }),
    defineField({
      name: 'parkingSpaces',
      title: 'Parking spaces',
      type: 'number',
      group: WEBSITE,
    }),
    defineField({
      name: 'yearBuilt',
      title: 'Year built',
      type: 'number',
      group: WEBSITE,
    }),
    defineField({
      name: 'featured',
      title: 'Featured listing',
      type: 'boolean',
      group: WEBSITE,
      initialValue: false,
    }),
    defineField({
      name: 'signature',
      title: 'Signature collection',
      type: 'boolean',
      group: WEBSITE,
      initialValue: false,
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      group: WEBSITE,
      rows: 8,
      validation: (rule) => rule.max(10000),
    }),
    defineField({
      name: 'mainImage',
      title: 'Cover / hero image',
      type: 'image',
      group: MEDIA_PHOTOS,
      options: {hotspot: true, metadata: ['blurhash', 'lqip', 'palette']},
    }),
    defineField({
      name: 'galleryLeadImage',
      title: 'Featured gallery image (optional)',
      type: 'image',
      group: MEDIA_PHOTOS,
      options: {hotspot: true, metadata: ['blurhash', 'lqip', 'palette']},
    }),
    defineField({
      name: 'gallery',
      title: 'Property Gallery',
      type: 'array',
      group: MEDIA_PHOTOS,
      description:
        'Use the upload box to add multiple photos together, or select from Media library.',
      components: {input: PropertyGalleryInput},
      of: [
        defineArrayMember({
          type: 'image',
          title: 'Image',
          components: {
            input: GalleryImageMemberInput,
          },
          options: {
            hotspot: true,
            metadata: ['blurhash', 'lqip', 'palette'],
          },
          fields: [
            defineField({
              name: 'alt',
              title: 'Alt text',
              type: 'string',
              description: 'Short description for accessibility and SEO.',
            }),
          ],
        }),
      ],
      validation: (rule) => rule.max(30),
    }),
    defineField({
      name: 'floorPlanImage',
      title: 'Floor plan',
      type: 'image',
      group: MEDIA_DOCS,
      options: {hotspot: true, metadata: ['blurhash', 'lqip', 'palette']},
    }),
    defineField({
      name: 'brochureFile',
      title: 'Brochure or PDF',
      type: 'file',
      group: MEDIA_DOCS,
      options: {
        accept: 'application/pdf,.pdf',
      },
    }),
    defineField({
      name: 'amenities',
      title: 'Amenities',
      type: 'array',
      group: WEBSITE,
      of: [{type: 'string'}],
    }),
    defineField({
      name: 'seoTitle',
      title: 'SEO title',
      type: 'string',
      group: SEO,
    }),
    defineField({
      name: 'seoDescription',
      title: 'SEO description',
      type: 'text',
      group: SEO,
      rows: 3,
    }),

    /* --- Legacy fields (older listings / Bazaraki / new-development) — keep until documents are migrated --- */
    defineField({
      name: 'newDevelopment',
      title: 'Legacy: new development flag',
      type: 'boolean',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'publishToBazaraki',
      title: 'Legacy: publishToBazaraki',
      type: 'boolean',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'bazarakiExternalId',
      title: 'Legacy: bazarakiExternalId',
      type: 'string',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'bazarakiListingStatus',
      title: 'Legacy: bazarakiListingStatus',
      type: 'string',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'bazarakiRubric',
      title: 'Legacy: bazarakiRubric',
      type: 'number',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'bazarakiDistrict',
      title: 'Legacy: bazarakiDistrict',
      type: 'number',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'lastUpdatedForFeed',
      title: 'Legacy: lastUpdatedForFeed',
      type: 'datetime',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'bazarakiAttrs',
      title: 'Legacy: bazarakiAttrs',
      type: 'object',
      group: LEGACY,
      hidden: true,
      readOnly: true,
      fields: [
        defineField({name: 'type', type: 'number'}),
        defineField({name: 'pool', type: 'number'}),
        defineField({name: 'parking', type: 'number'}),
        defineField({name: 'airConditioning', type: 'number'}),
        defineField({name: 'numberOfBedrooms', type: 'number'}),
        defineField({name: 'numberOfBathrooms', type: 'number'}),
        defineField({name: 'postalcode', type: 'string'}),
        defineField({name: 'mustHaves', type: 'string'}),
      ],
    }),
    defineField({
      name: 'geometry',
      title: 'Legacy: geometry',
      type: 'object',
      group: LEGACY,
      hidden: true,
      readOnly: true,
      fields: [
        defineField({name: 'latitude', type: 'number'}),
        defineField({name: 'longitude', type: 'number'}),
      ],
    }),
    defineField({
      name: 'phoneHide',
      title: 'Legacy: phoneHide',
      type: 'boolean',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'negotiablePrice',
      title: 'Legacy: negotiablePrice',
      type: 'boolean',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'exchange',
      title: 'Legacy: exchange',
      type: 'boolean',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'disallowChat',
      title: 'Legacy: disallowChat',
      type: 'boolean',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'whatsapp',
      title: 'Legacy: whatsapp',
      type: 'string',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'chosenPhone',
      title: 'Legacy: chosenPhone',
      type: 'string',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'itemLink',
      title: 'Legacy: itemLink',
      type: 'url',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'videoLink',
      title: 'Legacy: videoLink',
      type: 'url',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'videoUploadByUrl',
      title: 'Legacy: videoUploadByUrl',
      type: 'url',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'condition',
      title: 'Legacy: condition',
      type: 'number',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
    defineField({
      name: 'delivery',
      title: 'Legacy: delivery',
      type: 'number',
      group: LEGACY,
      hidden: true,
      readOnly: true,
    }),
  ],
  preview: {
    select: {
      title: 'title',
      status: 'status',
      media: 'mainImage',
    },
    prepare({title, status, media}) {
      const subtitle = status || undefined
      return {
        title: title || 'Property',
        subtitle,
        media,
      }
    },
  },
})
